import type { Country, ProviderPricing, WorkloadPreset } from "./types";

export const CATALOG_DATE = "2026-09-09";

export const countries: Country[] = [
  { code: "US", name: "United States", currency: "USD", usdRate: 1, recommendedRegion: "US East" },
  { code: "IN", name: "India", currency: "INR", usdRate: 95.07, recommendedRegion: "Mumbai" },
  { code: "GB", name: "United Kingdom", currency: "GBP", usdRate: 0.74, recommendedRegion: "London" },
  { code: "DE", name: "Germany", currency: "EUR", usdRate: 0.86, recommendedRegion: "Frankfurt" },
  { code: "CA", name: "Canada", currency: "CAD", usdRate: 1.37, recommendedRegion: "Toronto" },
  { code: "AU", name: "Australia", currency: "AUD", usdRate: 1.51, recommendedRegion: "Sydney" },
  { code: "SG", name: "Singapore", currency: "SGD", usdRate: 1.28, recommendedRegion: "Singapore" },
  { code: "JP", name: "Japan", currency: "JPY", usdRate: 148.2, recommendedRegion: "Tokyo" },
  { code: "BR", name: "Brazil", currency: "BRL", usdRate: 5.4, recommendedRegion: "São Paulo" },
  { code: "AE", name: "United Arab Emirates", currency: "AED", usdRate: 3.6725, recommendedRegion: "UAE" },
];

const commonRegions = {
  US: "US East",
  IN: "Mumbai / nearest available",
  GB: "London",
  DE: "Frankfurt",
  CA: "Toronto / Montréal",
  AU: "Sydney",
  SG: "Singapore",
  JP: "Tokyo",
  BR: "São Paulo / nearest available",
  AE: "UAE / nearest available",
};

/**
 * Normalized public list-price references. These rates intentionally model a
 * common denominator rather than every provider SKU. Every estimate links to
 * the provider source and identifies assumptions in the UI.
 */
export const providers: ProviderPricing[] = [
  {
    id: "gcp",
    name: "Google Cloud",
    shortName: "GCP",
    description: "Strong serverless containers, data services, and global infrastructure.",
    models: ["serverless", "container", "virtual-machine", "static"],
    regions: { ...commonRegions, IN: "asia-south1 (Mumbai)", US: "us-central1" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0.4,
      vcpuHour: 0.0864,
      memoryGbHour: 0.009,
      storageGbMonth: 0.02,
      egressGb: 0.12,
      databaseVcpuHour: 0.0826,
      databaseMemoryGbHour: 0.014,
      databaseStorageGbMonth: 0.17,
      databaseBaseMonthly: 0,
      gpuHour: 0.67,
    },
    free: { requestMillions: 2, vcpuHours: 50, memoryGbHours: 100, storageGb: 5, egressGb: 1 },
    sourceUrl: "https://docs.cloud.google.com/billing/v1/how-tos/catalog-api",
    sourceLabel: "Google Cloud Billing Catalog API",
    sourceKind: "official-api",
    ingestionCadence: "daily",
    updatedAt: CATALOG_DATE,
    operationalScore: 4,
    caveat: "Cloud Run and Compute Engine use different billing models; this comparison uses normalized list rates.",
  },
  {
    id: "aws",
    name: "Amazon Web Services",
    shortName: "AWS",
    description: "Broadest service catalog and regional coverage, with substantial pricing depth.",
    models: ["serverless", "container", "virtual-machine", "static"],
    regions: { ...commonRegions, IN: "ap-south-1 (Mumbai)", US: "us-east-1" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0.2,
      vcpuHour: 0.04048,
      memoryGbHour: 0.004445,
      storageGbMonth: 0.023,
      egressGb: 0.09,
      databaseVcpuHour: 0.096,
      databaseMemoryGbHour: 0.012,
      databaseStorageGbMonth: 0.115,
      databaseBaseMonthly: 0,
      gpuHour: 0.75,
    },
    free: { requestMillions: 1, storageGb: 5, egressGb: 1 },
    sourceUrl: "https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/using-the-aws-price-list-bulk-api.html",
    sourceLabel: "AWS Price List Bulk API",
    sourceKind: "official-api",
    ingestionCadence: "daily",
    updatedAt: CATALOG_DATE,
    operationalScore: 3,
    caveat: "Load balancers, NAT gateways, public IPv4, CloudWatch, and cross-zone traffic can add material cost.",
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    shortName: "Azure",
    description: "Enterprise-focused cloud with extensive Microsoft and hybrid integrations.",
    models: ["serverless", "container", "virtual-machine", "static"],
    regions: { ...commonRegions, IN: "Central India", US: "East US" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0.4,
      vcpuHour: 0.0864,
      memoryGbHour: 0.0108,
      storageGbMonth: 0.0184,
      egressGb: 0.087,
      databaseVcpuHour: 0.101,
      databaseMemoryGbHour: 0.013,
      databaseStorageGbMonth: 0.115,
      databaseBaseMonthly: 0,
      gpuHour: 0.8,
    },
    free: { requestMillions: 2, vcpuHours: 50, memoryGbHours: 100, storageGb: 5 },
    sourceUrl: "https://learn.microsoft.com/rest/api/cost-management/retail-prices/azure-retail-prices",
    sourceLabel: "Azure Retail Prices API",
    sourceKind: "official-api",
    ingestionCadence: "daily",
    updatedAt: CATALOG_DATE,
    operationalScore: 3,
    caveat: "Container Apps, Functions, and VMs price compute differently; enterprise agreements are not included.",
  },
  {
    id: "railway",
    name: "Railway",
    shortName: "Railway",
    description: "Developer-friendly container hosting with simple usage-based pricing.",
    models: ["container", "virtual-machine"],
    regions: { ...commonRegions, IN: "Singapore (nearest)", BR: "US East (nearest)", AE: "Europe (nearest)" },
    pricing: {
      baseMonthly: 20,
      requestMillion: 0,
      vcpuHour: 20 / 730,
      memoryGbHour: 10 / 730,
      storageGbMonth: 0.15,
      egressGb: 0.05,
      databaseVcpuHour: 20 / 730,
      databaseMemoryGbHour: 10 / 730,
      databaseStorageGbMonth: 0.15,
      databaseBaseMonthly: 0,
      gpuHour: null,
    },
    free: {},
    sourceUrl: "https://railway.com/pricing",
    sourceLabel: "Railway pricing",
    sourceKind: "official-page",
    ingestionCadence: "weekly",
    updatedAt: CATALOG_DATE,
    operationalScore: 5,
    caveat: "The Pro subscription is treated as a $20 monthly floor with included usage credit.",
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    shortName: "DigitalOcean",
    description: "Predictable virtual machines and managed services with generous transfer allowances.",
    models: ["container", "virtual-machine", "static"],
    regions: { ...commonRegions, IN: "Bengaluru", BR: "New York (nearest)", AE: "Frankfurt (nearest)" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0,
      vcpuHour: 0.03125,
      memoryGbHour: 0.006,
      storageGbMonth: 0.1,
      egressGb: 0.01,
      databaseVcpuHour: 0.06,
      databaseMemoryGbHour: 0.012,
      databaseStorageGbMonth: 0.2,
      databaseBaseMonthly: 15,
      gpuHour: 1.91,
    },
    free: { egressGb: 1000 },
    sourceUrl: "https://docs.digitalocean.com/reference/api/reference/sizes/",
    sourceLabel: "DigitalOcean Sizes API + pricing",
    sourceKind: "official-api",
    ingestionCadence: "daily",
    updatedAt: CATALOG_DATE,
    operationalScore: 4,
    caveat: "Compute is normalized from bundled Droplet prices; actual plans are discrete sizes.",
  },
  {
    id: "vercel",
    name: "Vercel",
    shortName: "Vercel",
    description: "Excellent frontend delivery and serverless web functions.",
    models: ["serverless", "static"],
    regions: { ...commonRegions, IN: "Mumbai / Singapore", AE: "Frankfurt" },
    pricing: {
      baseMonthly: 20,
      requestMillion: 0,
      vcpuHour: 0.128,
      memoryGbHour: 0.0106,
      storageGbMonth: 0.023,
      egressGb: 0.15,
      databaseVcpuHour: 0,
      databaseMemoryGbHour: 0,
      databaseStorageGbMonth: 0,
      databaseBaseMonthly: 0,
      gpuHour: null,
    },
    free: { requestMillions: 1, egressGb: 100 },
    sourceUrl: "https://vercel.com/docs/pricing/regional-pricing.md",
    sourceLabel: "Vercel regional pricing",
    sourceKind: "official-page",
    ingestionCadence: "weekly",
    updatedAt: CATALOG_DATE,
    operationalScore: 5,
    caveat: "Pro has a monthly platform fee and function duration/payload limits; external databases are separate.",
  },
  {
    id: "cloudflare",
    name: "Cloudflare",
    shortName: "Cloudflare",
    description: "Edge-first functions, CDN, and low-egress object storage.",
    models: ["serverless", "static"],
    regions: { ...commonRegions },
    pricing: {
      baseMonthly: 5,
      requestMillion: 0.3,
      vcpuHour: 1.8,
      memoryGbHour: 0,
      storageGbMonth: 0.015,
      egressGb: 0,
      databaseVcpuHour: 0,
      databaseMemoryGbHour: 0,
      databaseStorageGbMonth: 0.75,
      databaseBaseMonthly: 0,
      gpuHour: null,
    },
    free: { requestMillions: 10, storageGb: 10 },
    sourceUrl: "https://developers.cloudflare.com/workers/platform/pricing/",
    sourceLabel: "Cloudflare Workers pricing",
    sourceKind: "official-page",
    ingestionCadence: "weekly",
    updatedAt: CATALOG_DATE,
    operationalScore: 5,
    caveat: "Workers bill CPU milliseconds rather than provisioned vCPU; long-running compute is not comparable.",
  },
  {
    id: "render",
    name: "Render",
    shortName: "Render",
    description: "Managed web services, workers, cron jobs, and databases.",
    models: ["container", "virtual-machine", "static"],
    regions: { ...commonRegions, IN: "Singapore (nearest)", AE: "Frankfurt" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0,
      vcpuHour: 0.035,
      memoryGbHour: 0.012,
      storageGbMonth: 0.25,
      egressGb: 0.1,
      databaseVcpuHour: 0.055,
      databaseMemoryGbHour: 0.018,
      databaseStorageGbMonth: 0.3,
      databaseBaseMonthly: 19,
      gpuHour: null,
    },
    free: { egressGb: 100 },
    sourceUrl: "https://render.com/pricing",
    sourceLabel: "Render pricing",
    sourceKind: "official-page",
    ingestionCadence: "weekly",
    updatedAt: CATALOG_DATE,
    operationalScore: 5,
    caveat: "Instance sizes are discrete and managed database pricing starts at a plan minimum.",
  },
  {
    id: "fly",
    name: "Fly.io",
    shortName: "Fly.io",
    description: "Globally distributed applications running close to users.",
    models: ["container", "virtual-machine"],
    regions: { ...commonRegions, IN: "Singapore (nearest)", BR: "São Paulo", AE: "Frankfurt" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0,
      vcpuHour: 0.036,
      memoryGbHour: 0.0065,
      storageGbMonth: 0.15,
      egressGb: 0.02,
      databaseVcpuHour: 0.05,
      databaseMemoryGbHour: 0.01,
      databaseStorageGbMonth: 0.15,
      databaseBaseMonthly: 0,
      gpuHour: 0.8,
    },
    free: {},
    sourceUrl: "https://fly.io/docs/about/pricing/",
    sourceLabel: "Fly.io pricing",
    sourceKind: "official-page",
    ingestionCadence: "weekly",
    updatedAt: CATALOG_DATE,
    operationalScore: 3,
    caveat: "Regional network and managed Postgres architecture require careful operational planning.",
  },
  {
    id: "hetzner",
    name: "Hetzner Cloud",
    shortName: "Hetzner",
    description: "Low-cost virtual machines with strong European pricing.",
    models: ["container", "virtual-machine"],
    regions: { ...commonRegions, US: "Ashburn / Hillsboro", IN: "Singapore (nearest)", BR: "US East (nearest)", AE: "Nuremberg (nearest)" },
    pricing: {
      baseMonthly: 0,
      requestMillion: 0,
      vcpuHour: 0.011,
      memoryGbHour: 0.002,
      storageGbMonth: 0.052,
      egressGb: 0.001,
      databaseVcpuHour: 0.011,
      databaseMemoryGbHour: 0.002,
      databaseStorageGbMonth: 0.052,
      databaseBaseMonthly: 0,
      gpuHour: null,
    },
    free: { egressGb: 1000 },
    sourceUrl: "https://docs.hetzner.cloud/reference/cloud",
    sourceLabel: "Hetzner Cloud Pricing API",
    sourceKind: "official-api",
    ingestionCadence: "daily",
    updatedAt: CATALOG_DATE,
    operationalScore: 2,
    caveat: "Low list price comes with more self-management and fewer regions than hyperscalers.",
  },
];

export const workloadPresets: WorkloadPreset[] = [
  {
    id: "static-site",
    name: "Marketing or content site",
    shortDescription: "Mostly static pages, images, and occasional form/API calls.",
    guidance: "Start with static hosting and a CDN. Add serverless functions only for dynamic actions.",
    defaults: {
      workload: "static-site",
      model: "static",
      monthlyRequests: 1_000_000,
      averageDurationMs: 20,
      vcpu: 0.25,
      memoryGb: 0.25,
      instances: 1,
      activeHours: 20,
      storageGb: 10,
      egressGb: 50,
      databaseVcpu: 0,
      databaseMemoryGb: 0,
      databaseStorageGb: 0,
      databaseHours: 0,
      gpuHours: 0,
      highAvailability: false,
    },
  },
  {
    id: "api",
    name: "Public API or backend",
    shortDescription: "Request-driven API with variable traffic and a small database.",
    guidance: "Serverless is efficient for uneven traffic. Use containers when requests are long or traffic is steady.",
    defaults: {
      workload: "api",
      model: "serverless",
      monthlyRequests: 5_000_000,
      averageDurationMs: 220,
      vcpu: 1,
      memoryGb: 0.5,
      instances: 1,
      activeHours: 120,
      storageGb: 20,
      egressGb: 100,
      databaseVcpu: 1,
      databaseMemoryGb: 2,
      databaseStorageGb: 30,
      databaseHours: 730,
      gpuHours: 0,
      highAvailability: false,
    },
  },
  {
    id: "saas",
    name: "SaaS web application",
    shortDescription: "Always-on application with background jobs and a managed database.",
    guidance: "Use containers plus managed Postgres. Enable high availability after validating recovery requirements.",
    defaults: {
      workload: "saas",
      model: "container",
      monthlyRequests: 10_000_000,
      averageDurationMs: 280,
      vcpu: 2,
      memoryGb: 4,
      instances: 2,
      activeHours: 730,
      storageGb: 100,
      egressGb: 250,
      databaseVcpu: 2,
      databaseMemoryGb: 4,
      databaseStorageGb: 100,
      databaseHours: 730,
      gpuHours: 0,
      highAvailability: true,
    },
  },
  {
    id: "ecommerce",
    name: "Ecommerce store",
    shortDescription: "Transactional workload with traffic spikes and strict availability needs.",
    guidance: "Prioritize managed databases, backups, multiple instances, CDN caching, and tested failover.",
    defaults: {
      workload: "ecommerce",
      model: "container",
      monthlyRequests: 20_000_000,
      averageDurationMs: 350,
      vcpu: 2,
      memoryGb: 4,
      instances: 3,
      activeHours: 730,
      storageGb: 200,
      egressGb: 500,
      databaseVcpu: 4,
      databaseMemoryGb: 8,
      databaseStorageGb: 250,
      databaseHours: 730,
      gpuHours: 0,
      highAvailability: true,
    },
  },
  {
    id: "media-worker",
    name: "Media processing",
    shortDescription: "CPU-heavy video, image, or audio processing jobs.",
    guidance: "Use queued container workers. Estimate CPU runtime and outbound file delivery carefully.",
    defaults: {
      workload: "media-worker",
      model: "container",
      monthlyRequests: 100_000,
      averageDurationMs: 90_000,
      vcpu: 2,
      memoryGb: 4,
      instances: 2,
      activeHours: 300,
      storageGb: 200,
      egressGb: 1500,
      databaseVcpu: 1,
      databaseMemoryGb: 2,
      databaseStorageGb: 20,
      databaseHours: 730,
      gpuHours: 0,
      highAvailability: false,
    },
  },
  {
    id: "ai-inference",
    name: "AI inference service",
    shortDescription: "GPU-backed model inference with an API and model storage.",
    guidance: "GPU model, batching, utilization, and scale-to-zero behavior dominate cost. Benchmark before committing.",
    defaults: {
      workload: "ai-inference",
      model: "container",
      monthlyRequests: 1_000_000,
      averageDurationMs: 1200,
      vcpu: 4,
      memoryGb: 16,
      instances: 1,
      activeHours: 200,
      storageGb: 500,
      egressGb: 250,
      databaseVcpu: 1,
      databaseMemoryGb: 2,
      databaseStorageGb: 20,
      databaseHours: 730,
      gpuHours: 200,
      highAvailability: false,
    },
  },
];
